version: 2
updates:
  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: development

  - package-ecosystem: pnpm
    directory: /playground
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(playground-deps)"

  - package-ecosystem: pnpm
    directory: /docs
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(docs-deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(actions)"
